# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
[@](bold bg:black fg:red)\
$hostname\
[](bg:black)\
[](bg:blue fg:black)\
$directory\
[](fg:blue bg:green)\
$git_branch\
$git_state\
$git_status\
[](fg:green bg:bright-black)\
$python\
$golang\
$rust\
$terraform\
[](fg:bright-black bg:none)
$character
"""

# Inserts a blank line between shell prompts
add_newline = true

right_format = """
[\\[](bg:black fg:blue)\
$time
[\\]](bg:black fg:blue)
"""

[character]
disabled = false

[directory]
disabled = false
format = "[ $path$read_only]($style)"
style = "bg:blue fg:black"
truncate_to_repo = false
truncation_length = 4
truncation_symbol = ".../"

[golang]
format = "[ $symbol($version)]($style)"
style = "fg:white bg:bright-black"
symbol = ""
version_format = "${major}.${minor}"

[hostname]
disabled = false
format = "[$hostname$ssh_symbol]($style)"
ssh_only = false
ssh_symbol = "🌐"
style = "bg:black fg:green"

[git_branch]
format = "[ $symbol $branch(:$remote_branch)]($style)"
style = "fg:black bg:green"
symbol = ""

[git_state]
format = "[$state( $progress_current/$progress_total)]($style) "
style = "bold fg:black bg:green"

[git_status]
ahead = " ⬆"
behind = " ⬇"
conflicted = " ="
deleted = " ✖"
diverged = " ⇕"
format = "([$all_status$ahead_behind ]($style))"
modified = " ✱"
renamed = " ➙"
staged = " +"
stashed = " S"
style = "fg:black bg:green"
untracked = " ?"

[python]
disabled = false
format = "[ $symbol($version)]($style)"
style = "fg:white bg:bright-black"
symbol = ""
version_format = "${major}.${minor}"

[rust]
format = "[ $symbol($version)]($style)"
style = "fg:white bg:bright-black"
symbol = ""
version_format = "${major}.${minor}"

[terraform]
format = "[ $symbol($version)]($style)"
style = "fg:white bg:bright-black"
symbol = "TF"
version_format = "${major}.${minor}"

[time]
disabled = false
format = "[$time]($style)"
style = "bg:black fg:green"

[username]
disabled = false
format = "[$user]($style)"
show_always = true
style_root = "bold bg:black fg:blue"
style_user = "bg:black fg:blue"
